image: node:latest

stages:
    - install
    - test

install:
   stage: install
   script:
      - npm install
   artifacts:
      name: "artifacts"
      untracked: true
      expire_in: 30 mins
      paths:
        - .npm/
        - node_modules/

test:
   stage: test
   script:
      -  npm run test:ci
   dependencies:
      - install

linting:
   stage: test
   script:
      - npm run lint