image: node:latest 

stages:
  - lint
  - test

Code linting:
  stage: lint
  before_script:
    - npx install-peerdeps --dev @lnu/eslint-config
  script:
      npx eslint .

Code testing: 
  stage: test
  before_script: 
    - npm install --save-dev jest supertest dotenv cross-env
  script:
    - cross-env NODE_OPTIONS=--experimental-vm-modules npx jest --testTimeout=10000 --runInBand --detectOpenHandles --verbose --watchAll
