image: node:latest 

stages:
  - install
  - lint
  - test

Install:
 stage: install
 script:
    - npm install
 artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/


Code linting:
  stage: lint
  script:
      npm run lint

Code testing: 
  stage: test
  script:
      - cross-env NODE_OPTIONS=--experimental-vm-modules npx jest --testTimeout=20000 --runInBand --detectOpenHandles --verbose --forceExit 
  dependencies:
        - install